/**
 * Fix 18 Closure: Background runner must not overwrite final output
 *
 * Validates that:
 * 1. Background completion performs no second canonical write (upsertModuleOutput removed)
 * 2. Background and interactive outputs have identical generation IDs (sole-writer principle)
 * 3. Missing canonical output after core completion is treated as an error
 * 4. Housekeeping and verification disclosures survive background completion
 *
 * Strategy: Since resume-stale-pipelines.ts is an SDK API that requires integrations,
 * we verify the contract structurally by importing the module and confirming:
 * - upsertModuleOutput is NOT imported
 * - The file performs a SELECT (verification) not INSERT after completion
 * - The error path marks runs failed when output is missing
 *
 * Run: npx tsx server/apis/pipeline/__tests__/fix18-closure-background-runner-output.test.ts
 */

import * as fs from "fs";
import * as path from "path";

function assert(condition: boolean, msg: string): void {
  if (!condition) { console.error(`FAIL: ${msg}`); process.exit(1); }
}

// ---------------------------------------------------------------------------
// Test 1: upsertModuleOutput is NOT imported in resume-stale-pipelines
// ---------------------------------------------------------------------------
console.log("Test 1: No upsertModuleOutput import in background runner");
{
  const source = fs.readFileSync(
    path.resolve("server/apis/pipeline/resume-stale-pipelines.ts"),
    "utf-8"
  );

  assert(
    !source.includes("upsertModuleOutput"),
    "resume-stale-pipelines.ts should NOT reference upsertModuleOutput"
  );
}

// ---------------------------------------------------------------------------
// Test 2: Background runner does NOT construct a full report for persistence
// ---------------------------------------------------------------------------
console.log("Test 2: No markdown report construction in background runner");
{
  const source = fs.readFileSync(
    path.resolve("server/apis/pipeline/resume-stale-pipelines.ts"),
    "utf-8"
  );

  // The old code had this distinctive report template
  assert(
    !source.includes("Generated by background pipeline runner"),
    "Background runner should not generate its own report markdown"
  );

  // Should not reconstruct findings as markdown
  assert(
    !source.includes("findingsMarkdown"),
    "Background runner should not have findingsMarkdown reconstruction"
  );
}

// ---------------------------------------------------------------------------
// Test 3: Background runner performs output verification (SELECT not INSERT)
// ---------------------------------------------------------------------------
console.log("Test 3: Background runner verifies canonical output exists");
{
  const source = fs.readFileSync(
    path.resolve("server/apis/pipeline/resume-stale-pipelines.ts"),
    "utf-8"
  );

  // Must contain a verification query
  assert(
    source.includes("SELECT id FROM module_outputs WHERE module_run_id"),
    "Background runner should verify module_outputs existence via SELECT"
  );

  // Must contain the verification label
  assert(
    source.includes("Verify canonical output exists"),
    "Should have labeled verification query"
  );
}

// ---------------------------------------------------------------------------
// Test 4: Missing canonical output after core completion marks run failed
// ---------------------------------------------------------------------------
console.log("Test 4: Missing output → error state, not silent");
{
  const source = fs.readFileSync(
    path.resolve("server/apis/pipeline/resume-stale-pipelines.ts"),
    "utf-8"
  );

  // Must mark the run as failed when output is missing
  assert(
    source.includes("canonical output missing after core completion"),
    "Should detect and report missing canonical output"
  );

  assert(
    source.includes("status = 'failed'::module_status"),
    "Should mark run as failed when canonical output missing"
  );
}

// ---------------------------------------------------------------------------
// Test 5: runPipelineCore is the sole output writer (structural verification)
// The interactive path also uses runPipelineCore, so identical code path = identical output
// ---------------------------------------------------------------------------
console.log("Test 5: Sole-writer principle ensures identical outputs");
{
  const source = fs.readFileSync(
    path.resolve("server/apis/pipeline/resume-stale-pipelines.ts"),
    "utf-8"
  );

  // Must call runPipelineCore (which is the sole writer)
  assert(
    source.includes("runPipelineCore(ctx"),
    "Background runner must call runPipelineCore"
  );

  // Must NOT call any other write to module_outputs
  const moduleOutputsWrites = source.match(/INSERT\s+INTO\s+module_outputs/gi);
  assert(
    moduleOutputsWrites === null,
    "Background runner must not INSERT INTO module_outputs directly"
  );
}

// ---------------------------------------------------------------------------
// Test 6: Housekeeping/verification findings are preserved through the core path
// (Structural: the background runner passes through to runPipelineCore which handles them)
// ---------------------------------------------------------------------------
console.log("Test 6: No post-processing that could strip housekeeping/verification");
{
  const source = fs.readFileSync(
    path.resolve("server/apis/pipeline/resume-stale-pipelines.ts"),
    "utf-8"
  );

  // Should NOT filter findings in any way after runPipelineCore returns
  assert(
    !source.includes(".filter("),
    "Background runner should not filter findings post-completion"
  );

  // Should NOT re-map or transform findings
  const findingsMapCount = (source.match(/result\.result\.findings\.map/g) || []).length;
  assert(
    findingsMapCount === 0,
    "Background runner should not .map() over result findings"
  );
}

// ---------------------------------------------------------------------------
// Test 7: Numeric-dependent runs can resume from persisted checkpoint
// ---------------------------------------------------------------------------
console.log("Test 7: Numeric-dependent modules check for persisted numeric report");
{
  const source = fs.readFileSync(
    path.resolve("server/apis/pipeline/resume-stale-pipelines.ts"),
    "utf-8"
  );

  // Must load numeric_report_json when available
  assert(
    source.includes("numeric_report_json"),
    "Should load persisted numeric_report_json for numeric-dependent modules"
  );

  // Must skip numeric-dependent modules when report is unavailable
  assert(
    source.includes("numeric-dependent module without persisted numeric report"),
    "Should skip numeric modules when report is unavailable"
  );
}

console.log("\n✓ All 7 Fix 18 closure tests passed");
